# -- 코드를 입력하세요
# SELECT COUNT(USER_ID) as 'USERS'
# FROM USER_INFO
# WHERE (YEAR(JOINED) = '2021') AND ( 20 <= AGE <= 29);

SELECT COUNT(USER_ID) as 'USERS'
FROM USER_INFO
WHERE YEAR(JOINED) = '2021' AND ( AGE BETWEEN 20 and 29);
