# -- 코드를 입력하세요


SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) as 'prod'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING prod >= 7
ORDER BY prod DESC, CAR_ID DESC;

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID = 1;
