-- 코드를 작성해주세요
SELECT COUNT(f.ID) as 'FISH_COUNT', i.FISH_NAME as 'FISH_NAME'
FROM FISH_INFO as f
    INNER JOIN FISH_NAME_INFO as i ON f.FISH_TYPE = i.FISH_TYPE
GROUP BY i.FISH_TYPE, i.FISH_NAME
ORDER BY FISH_COUNT DESC