-- 코드를 작성해주세요
SELECT ti.ITEM_ID, ti.ITEM_NAME, ti.RARITY
FROM ITEM_INFO ti
WHERE ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IN (
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE')
    )
ORDER BY ITEM_ID DESC;