-- 코드를 작성해주세요
SELECT c.ID,	c.GENOTYPE,	p.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA c
    INNER JOIN ECOLI_DATA p
    ON p.ID = c.PARENT_ID 
    AND (p.GENOTYPE & c.GENOTYPE = p.GENOTYPE)
ORDER BY c.ID ASC;

