-- 코드를 입력하세요
SELECT th.FLAVOR
FROM FIRST_HALF th
    INNER JOIN ICECREAM_INFO ti ON th.FLAVOR = ti.FLAVOR
    AND ti.INGREDIENT_TYPE = 'fruit_based'
    AND th.TOTAL_ORDER > 3000
ORDER BY th.TOTAL_ORDER DESC;
