-- 코드를 입력하세요
WITH cte_p AS (
SELECT PRODUCT_ID, (PRICE DIV 10000 * 10000) as 'PROD_PRICE'
    FROM PRODUCT
)
SELECT cte_p.PROD_PRICE as 'PRICE_GROUP', COUNT(t_p.PRODUCT_ID) as PRODUCTS
FROM PRODUCT t_p JOIN cte_p ON cte_p.PRODUCT_ID = t_p.PRODUCT_ID
GROUP BY cte_p.PROD_PRICE
ORDER BY PRICE_GROUP